Do not convert Rack::Response to Rack::Response
While using https://github.com/aserafin/grape_logging grape middleware after an upgrading grape from 0.11 to 0.12 I've been stuck with an issue:

```
NoMethodError (undefined method `downcase' for 2:Fixnum)
```

That's because `Middleware#response` tries to convert `Rack::Response` to `Rack::Response` and fails.